# Generated by Django 4.2.5 on 2023-11-03 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='contenido',
            new_name='mensaje',
        ),
    ]
