# Generated by Django 4.2.5 on 2023-11-03 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0002_rename_contenido_comentario_mensaje'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='autor',
            new_name='titulo',
        ),
    ]
