# Generated by Django 4.2.5 on 2023-11-04 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0008_comentario_autor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='fecha_publicacion',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='mensaje',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='autor',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='titulo',
        ),
    ]
