# Generated by Django 4.2.5 on 2023-10-20 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nueva', '0002_alter_paleta_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='paleta',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
    ]
