# Generated by Django 4.2.5 on 2023-10-21 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nueva', '0004_rename_img_paleta_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paleta',
            old_name='marca',
            new_name='detalle',
        ),
        migrations.RenameField(
            model_name='paleta',
            old_name='modelo',
            new_name='titulo',
        ),
    ]
