# Generated by Django 4.2.5 on 2023-10-20 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='cursos'),
        ),
    ]
